<?php


namespace Contact\Providers;


use Illuminate\Support\ServiceProvider;
use Contact\Hook\ContactHook;


class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[ContactHook::class,'handle'],8);
    }
}
