<?php


namespace Transaction\Providers;


use Illuminate\Support\ServiceProvider;
use Transaction\Hook\TransactionHook;


class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[TransactionHook::class,'handle'],11);
    }
}
