<?php


namespace Users\Providers;

use Illuminate\Support\ServiceProvider;
use Users\Hook\UsersHook;

class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[UsersHook::class,'handle'],7);
    }

}
