<?php


namespace Company\Providers;


use Illuminate\Support\ServiceProvider;
use Company\Hook\CompanyHook;

class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
//        add_action('wadmin-register-menu',[CompanyHook::class,'handle'],2);
    }
}
