<?php


namespace Project\Providers;


use Illuminate\Support\ServiceProvider;
use Project\Hook\ProjectHook;


class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[ProjectHook::class,'handle'],15);
    }
}
