<?php


namespace Setting\Providers;


use Illuminate\Support\ServiceProvider;
use Setting\Hook\SettingHook;


class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[SettingHook::class,'handle'],10);
    }
}
