<?php


namespace Page\Providers;


use Illuminate\Support\ServiceProvider;
use Page\Hook\PageHook;


class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[PageHook::class,'handle'],5);
    }
}
